// Mapping of Binance symbols to coin metadata
export const COIN_METADATA: Record<string, { id: string; name: string; symbol: string }> = {
  btcusdt: { id: "btc", name: "Bitcoin", symbol: "BTC" },
  ethusdt: { id: "eth", name: "Ethereum", symbol: "ETH" },
  bnbusdt: { id: "bnb", name: "BNB", symbol: "BNB" },
  solusdt: { id: "sol", name: "Solana", symbol: "SOL" },
  xrpusdt: { id: "xrp", name: "XRP", symbol: "XRP" },
  adausdt: { id: "ada", name: "Cardano", symbol: "ADA" },
  dogeusdt: { id: "doge", name: "Dogecoin", symbol: "DOGE" },
  trxusdt: { id: "trx", name: "TRON", symbol: "TRX" },
  maticusdt: { id: "matic", name: "Polygon", symbol: "MATIC" },
  linkusdt: { id: "link", name: "Chainlink", symbol: "LINK" },
  ltcusdt: { id: "ltc", name: "Litecoin", symbol: "LTC" },
  avaxusdt: { id: "avax", name: "Avalanche", symbol: "AVAX" },
  dotusdt: { id: "dot", name: "Polkadot", symbol: "DOT" },
  atomusdt: { id: "atom", name: "Cosmos", symbol: "ATOM" },
  usdcusdt: { id: "usdc", name: "USD Coin", symbol: "USDC" },
  suiusdt: { id: "sui", name: "Sui", symbol: "SUI" },
  tonusdt: { id: "ton", name: "Toncoin", symbol: "TON" },
  hbarusdt: { id: "hbar", name: "Hedera", symbol: "HBAR" },
  nearusdt: { id: "near", name: "NEAR Protocol", symbol: "NEAR" },
};
